#' Genetic algorithm
#'
#' A genetic algorithm for optimization of the clustFBE loss function (sum of
#' within cluster sum of squares).
#'
#' @param X Matrix of shape (`n`, `nrep`) where `n` is the length of the time
#' series observations and `nrep` is the number of independent replicates.
#' @param nclust Integer. the number of clusters to consider. Can be 1.
#' @param nbands Integer. the number of bands to consider. Must be at least 2.
#' @param popsize Integer. Size of the population carried through each
#' generation of the GA.
#' @param pop Optional. A population as generated by \code{\link{pop_init}}. Can
#' be useful for obtaining multiple solutions from the same initial population.
#' @param nparents Integer. The number of parents to select that will be
#' subsequently subjected to crossover and/or mutation in each generation. Must
#' be at least 2. Defaults to twice the population size.
#' @param nelite Integer. The number of elites (most fit) solutions to carry
#' over from the previous generation into the current generation at each
#' iteration of the GA. Default is `2`. This can be set to `0` to prevent
#' the implementation of an elitism policy.
#' @param pcrossover Probability that any two selected parents will be crossed.
#' Setting this to `0` means no crossover will be performed. Default is `0.5`.
#' @param pmutate Probability that any endpoint or collapsed measure of a single
#' solution will be subjected to mutation (independent of the other values and
#' other solutions). Default is `0.25`.
#' @param endpoint_range Integer or vector of integers. The total maximum width
#' of the window in which any new endpoint is selected. See details below for
#' default values.
#' @param collapsed_range Double or vector of double. the total width of the
#' window in which any new collapsed measure is shifted. See details below for
#' default values.
#' @param maxgen Integer. The maximum number of generations the GA is allowed
#' to run. Defaults to `500`.
#' @param maxrun Integer. The maxumum number of generations the GA is allowed
#' to run without significant improvement in the maximum fitness of the
#' population. Defaults to `50`.
#' @param tol Double. The percent difference above which a significant
#' improvement in maximum fitness is declared. Larger values mean that larger
#' improvements are needed to increase the run count and therefore lead to
#' shorter convergence times. Defaults to `1e-3` (0.1%).
#' @param s the size of the window to shift each evenly spaced frequency within
#' when initializing endpoints for each solution. Defaults to 10% of the number
#' of Fourier frequencies.
#' @param ntapers Integer. The number of tapers to use in estimation of the
#' replicate spectra from `X`. Defaults to the floor of the square root of
#' length of the time series in `X`.
#' @param verbose Boolean. Whether to print progress of the algorithm to the
#' console. Defaults to `FALSE`.
#'
#' @return A list with the following components.
ga <- function(X, nclust, nbands, popsize = 50, pop = NULL,
               nparents = 2 * popsize, nelite = 2, pcrossover = 0.5,
               pmutate = 0.25, endpoint_range = NULL, collapsed_range = NULL,
               maxgen = 500, maxrun = 50, tol = 1e-3, s = NULL,
               ntapers = floor(sqrt(dim(X)[1])), verbose = F) {
  # estimate spectra from X
  if (is.vector(X)) X <- as.matrix(X)
  mtout <- sine_multitaper(X, ntapers = ntapers)
  mtfreq <- mtout$mtfreq
  spec <- mtout$mtspec
  nfreq <- dim(spec)[1]

  # ensure that the number of parents is at least 2
  if (nparents < 2) {
    warning(paste0("Number of parents specified (nparents = ", nparents,
                   ") was too small. nparents = 2 will be used."))
    nparents <- 2
  }

  # mutation parameters default to adaptive values if none are specified
  # endpoint range
  if (is.null(endpoint_range)) {
    # monotonically decreasing endpoint mutation range over generations
    endpoint_range <- floor(seq(from = floor(0.1 * nrow(spec)),
                                to = 1,
                                length = maxgen))
  } else if (is.integer(endpoint_range)) {
    # use same value for each generation
    endpoint_range <- rep(endpoint_range, maxgen)
  } else if (is.vector(endpoint_range)) {
    if (length(endpoint_range) < maxgen) {
      stop(paste0("If providing a vector of endpoint mutation ranges for
                  adaptive mutation, ensure the length of this vector is
                  at least the maximum number of allowed generations (",
                  maxgen, ")."))
    }
  }

  # collapsed measure range
  if (is.null(collapsed_range)) {
    # monotonically decreasing endpoint mutation range over generations
    collapsed_range <- seq(from = 0.2 * max(spec),
                           to = 0.01 * sd(spec),
                           length = maxgen)
  } else if (is.double(collapsed_range)) {
    # use same value for each generation
    collapsed_range <- rep(collapsed_range, maxgen)
  } else if (is.vector(collapsed_range)) {
    if (length(collapsed_range) < maxgen) {
      stop(paste0("If providing a vector of collapsed measure mutation ranges
                  for adaptive mutation, ensure the length of this vector is
                  at least the maximum number of allowed generations (",
                  maxgen, ")."))
    }
  }

  # checks on maxgen and maxrun
  if (maxgen < 1) {
    stop("maxgen must be at least 1. Recommended setting is 500.")
  }
  if (maxrun < 1) {
    stop("maxrun must be at least 1. Recommended setting is 100")
  }
  if (maxrun > maxgen) {
    maxrun <- maxgen
    warning("maxrun greater than maxgen so convergence will be declared only
            when mxagen number of generations have been completed.
            Recommended setting is maxrun = 100.")
  }
  if (tol > 1) {
    tol <- 1
    warning("Tolerance set to 1. Recommended setting is 1e-3.")
  }
  if (tol < 1e-3) {
    warning("Tolerance was set below recommended value of 1e-3 which may
            cause longer than expected convergence times.")
  }

  # set s
  if (is.null(s)) s <- floor(0.1 * dim(spec)[1])

  # STEP 1 - population initialization
  if (popsize < 1) {
    stop("popsize must be at least 1. Recommended setting is 50.")
  }
  if (is.null(pop)) {
    pop <- pop_init(popsize, nclust, nbands, spec, s)
  } else {
    popsize <- length(pop)
  }

  # STEP 2 - initial evaluation of population
  fitness_values <- evaluate(pop, spec)
  if (nelite > 0) {
    # rank the population by fitness value
    u <- rank(-fitness_values, ties.method = "random")

    # get the top nelite ranked members and their fitness values
    elites <- pop[which(u %in% seq_len(nelite))]
    elite_fitness_values <- fitness_values[which(u %in% seq_len(nelite))]
  }

  # initialize monitoring
  gennum <- runlength <- 0
  avgfit <- maxfit <- ninfeasible <- rep(0, maxgen + 1)
  avgfit[gennum + 1] <- mean(fitness_values)
  maxfit[gennum + 1] <- max(fitness_values)
  ninfeasible[gennum + 1] <- sum(fitness_values == 1e-50)
  if (verbose) {
    cat(paste0(
      "START \t\t AVG FIT: ", round(avgfit[gennum + 1], 5),
      "\t\t MAX FIT: ", round(maxfit[gennum + 1], 5)
    ), "\n")
  }

  # iterate until convergence
  while (gennum < maxgen & runlength <= maxrun) {
    gennum <- gennum + 1 # increase generation count

    # parent selection by FPS via SUS
    parents <- parent_selection(pop, nparents, fitness_values)

    # crossover
    if (pcrossover > 0) {
      # number of pairs
      nmating <- floor(nparents / 2)
      # randomly pair the members of the current population
      mating <- matrix(sample(1:(2 * nmating), size = 2 * nmating), ncol = 2)
      for (i in seq_len(nmating)) {
        if (runif(1) < pcrossover) {
          # perform mutation (otherwise they are left alone)
          cout <- crossover(parents[[mating[i, 1]]], parents[[mating[i, 2]]])
          parents[[mating[i, 1]]] <- cout$c1
          parents[[mating[i, 2]]] <- cout$c2
        }
      }
    }

    # mutation
    for (i in seq_len(nparents)) {
      # mutate the current member
      mutated <- mutate(parents[[i]],
                        pmutate,
                        endpoint_range[gennum],
                        collapsed_range[gennum],
                        nfreq)
      # cluster the spectra on the basis of this mutated solution
      # if the mutated solution results in an infeasible solution,
      # the mutations are discarded and the current solution is left as is
      mutated_labels <- apply(dist_mat(spec, mutated), 1, which.min)
      if (length(unique(mutated_labels)) == nclust) parents[[i]] <- mutated
    }

    # evaluation and rank selection of offspring
    # evaluate the children that were created via crossover and/or mutation
    # of the selected parents.
    # children are evaluated and ranked. only the top popsize of them are
    # allowed to survive into the next generation.
    # the previous generation from which parents were selected is discarded.
    fitness_values <- evaluate(parents, spec)
    u <- rank(-fitness_values, ties.method = "random")
    pop <- parents[u <= popsize]
    fitness_values <- fitness_values[u <= popsize]

    # elitism (if specified)
    if (nelite > 0) {
      # rank the current population and the elites of the previous generation
      u <- rank(-c(fitness_values, elite_fitness_values),
                ties.method = "random")

      # use rank selection to permit elites that are better than at least one
      # of the children selected above to be carried over
      pop <- c(pop, elites)[u <= popsize]
      fitness_values <- c(fitness_values, elite_fitness_values)[u <= popsize]

      # re-rank the new population which may contain the elites from the
      # previous generation to get the new elites of the current generation
      u <- rank(-c(fitness_values, elite_fitness_values),
                ties.method = "random")
      elites <- c(pop, elites)[which(u %in% seq_len(nelite))]
      elite_fitness_values <- c(fitness_values, elite_fitness_values)[which(u %in% seq_len(nelite))]
    }

    # monitoring
    avgfit[gennum + 1] <- mean(fitness_values)
    maxfit[gennum + 1] <- max(fitness_values)
    ninfeasible[gennum + 1] <- sum(fitness_values == 1e-50)
    prevmfit <- maxfit[gennum]
    currmfit <- maxfit[gennum + 1]
    if ((currmfit - prevmfit) / prevmfit < tol) {
      runlength <- runlength + 1
    } else {
      runlength <- 0
    }
    if (verbose & gennum %% 25 == 0) {
      cat(paste0(
        "GEN ", gennum, "\t\t AVG FIT: ", round(avgfit[gennum + 1], 5),
        "\t\t MAX FIT: ", round(maxfit[gennum + 1], 5)
      ), "\n")
    }
  }

  # determine solution
  solution <- pop[[which.max(fitness_values)]]
  labels <- apply(dist_mat(spec, solution), 1, which.min)
  endpoints_index <- solution[, 1:(nbands - 1), drop = FALSE]
  endpoints <- endpoints_index
  for (j in 1:nclust) endpoints[j, ] <- mtfreq[endpoints_index[j, ]]
  collapsed <- avg_collapsed_by_index(spec, endpoints_index, labels)

  # compute internal validation index
  si <- selection_index(spec, labels, endpoints_index, collapsed)

  return(list(
    X = X,
    spec = spec,
    labels = labels,
    endpoints_index = endpoints_index,
    endpoints = endpoints,
    collapsed = collapsed,
    rep_collapsed = rep_collapsed_by_index(spec, endpoints_index, labels),
    loss = 1 / fitness_values[which.max(fitness_values)],
    avgfit = avgfit[1:(gennum + 1)],
    maxfit = maxfit[1:(gennum + 1)],
    ninfeasible = ninfeasible[1:(gennum + 1)],
    si = si,
    params = list(
      nclust = nclust,
      nbands = nbands,
      popsize = popsize,
      nparents = nparents,
      nelite = nelite,
      pcrossover = pcrossover,
      pmutate = pmutate,
      endpoint_range = endpoint_range,
      collapsed_range = collapsed_range,
      maxgen = maxgen,
      maxrun = maxrun,
      tol = tol
    )
  ))

}
