#' Parent selection
#'
#' Select a specified number of parents from a population using fitness
#' proportional selection via stochastic universal sampling (SUS).
#'
#' @param pop A population of solutions as generated by \code{\link{pop_init}}.
#' @param nparents Integer. Number of parents from `pop` to return. Assumed
#' that `nparents > 1`.
#' @param fitness_values Vector of length `length(pop)` which gives the
#' fitness value of each member of the population.
#'
#' @return A list of similar structure to `pop` of the selected parents.
parent_selection <- function(pop, nparents, fitness_values) {
  p <- cumsum(fitness_values / sum(fitness_values))
  s <- stochastic_universal_sampling(p, nparents)
  return(pop[s])
}

#' Stochastic Universal Sampling (SUS)
#'
#' This particular implementation is based on pseudocode in "Introduction to
#' Evolutionary Computing", 2e by Eiben and Smith (2015).
#'
#' @param cdf cumulative distribution function.
#' @param n number of items to select.
#'
#' @return integer indices of selected items.
stochastic_universal_sampling <- function(cdf, n) {
  cr <- i <- 1
  r <- runif(1, min = 0, max = 1 / n); s <- vector("integer", n)
  while (cr <= n) {
    while (r <= cdf[i]) {
      s[cr] <- i; r <- r + (1 / n); cr <- cr + 1
    }
    i <- i + 1
  }
  return(s)
}
